CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'seungpar'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'seungpar'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';
